<div class="alert alert-info"> <b>Привет Александр! 👋</b> 

Рада познакомиться 🙃  

Спасибо большое за твою работу и комментарии, я постаралась всё учесть.

Посмотрим насколько получилось по твоей следующей обратной связи 🤓  

Пробовала доработать 7 раздел, но не осилила(</div>

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №2__

Розалия, рад тебя видеть =) Спасибо за обратную связь и правки

<div style="border:solid green 2px; padding: 20px">
    
<b>Розалия, привет!</b> Мы рады тебя видеть на территории код-ревьюеров 😎. Ты проделала большую работу над проектом, но давай познакомимся и сделаем его еще лучше! У нас тут своя атмосфера и несколько правил:


1. Меня зовут Александр Матвеевский. Я работаю код-ревьюером, моя основная цель — не указать на совершенные тобою ошибки, а поделиться своим опытом и помочь тебе стать дата-специалистом.
2. Общаемся на ты.
3. Если хочешь написать, спросить - не нужно стесняться. Только выбери свой цвет для комментария.  
4. Это учебный проект, тут можно не бояться сделать ошибку.  
5. У нас с тобой 6 попыток для сдачи проекта.  
6. Let's Go!

---

Я буду красить комментарии цветом, пожалуйста, не удаляй их:

<div class="alert alert-block alert-danger">✍
    

__Комментарий от ревьюера №1__

Такой комментарий нужно исправить обязательно, он критически влияет на удачное выполнение проекта.
</div>
    
---

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__


Такой комментарий является рекомендацией или советом. Можешь использовать их на своё усмотрение.
</div>

---

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Такой комментарий  говорит о том, что было сделано что-то качественное и правильное =)
</div>
    
---
    
Предлагаю работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии — пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:   
    
<div class="alert alert-info"> <b>Комментарии студента:</b> Например, вот так.</div>
    
Всё это поможет выполнить повторную проверку твоего проекта оперативнее. Если будут какие-нибудь вопросы по моим комментариям, пиши, будем разбираться вместе :)    
    
---

# Анализ сервиса аренды самокатов GoFast.

## Описание проекта (#description_project)
<a id="description_project"></a>

Анализ популярного сервиса аренды самокатов `GoFast`. Задача — проанализировать данные и проверить некоторые гипотезы, которые могут помочь бизнесу вырасти.

Чтобы совершать поездки по городу, пользователи сервиса GoFast пользуются мобильным приложением. Сервисом можно пользоваться:
- **без подписки:**
    - абонентская плата отсутствует;
    - стоимость одной минуты поездки — 8 рублей;
    - стоимость старта (начала поездки) — 50 рублей;
- **с подпиской Ultra:**
    - абонентская плата — 199 рублей в месяц;
    - стоимость одной минуты поездки — 6 рублей;
    - стоимость старта — бесплатно.

*Цель исследования:*
1. Проанализировать данные о пользователях, подписках и поездках из представленных датасетов.
2. Найти `общие черты и особенности` представленных данных о частоте встречаемых городов, соотношении пользователей с подпиской и без, возраст пользователей, расстояние и продолжительность поездок.
3. Определить доли пользователей с подпиской и без.
4. Визуализировать информацию о расстоянии и времени поездок для пользователей обеих категорий.
5. Агрегация данных о поездках (суммарному расстоянию, количеству поездок и времени для каждого пользователя помесячно) с разбивкой по категориям пользователей.
6. Проверить гипотезы: по увеличению количества пользователей с подпиской, по оптимальному расстоянию одной поездки, сумме выручки пользователей с подпиской и без неё, снижению количества обращений в техподдержку после обновления серверов.
7. Проверить гипотезу по продлению подписки после проведённой акции, выяснить какое минимальное количество промокодов нужно разослать, чтобы вероятность не выполнить план была примерно 5%.
8. Построить примерный график распределения и оценить вероятность того, что уведомление в приложении от отдела маркетинга откроют не более 399,5 тыс. пользователей.

*Ход исследования:*
1. Загрузка и оценка качества данных .
2. Предобработка и корректировка полученных данных.
3. Исследовательский анализ данных по поставленным вопросам.
4. Визуализация проведённых исследований.
5. Проверка гипотез.
6. Формулирование выводов и рекомендаций для увеличения количества пользователей и выручки сервиса аренды самокатов `GoFast`.


## Описание данных (#description_data)

В основных данных есть информация о пользователях, их поездках и подписках. Информация представлена в трёх датасетах. Файлы `users_go.csv`, `rides_go.csv` и `subscriptions_go.csv`   

Структура представленных файлов:

- Пользователи — `users_go.csv`:
    - user_id — уникальный идентификатор пользователя;
    - name — имя пользователя; 
    - age — возраст;
    - city — город;
    - subscription_type — тип подписки (free, ultra).
- Поездки — `rides_go.csv`:
    - user_id — уникальный идентификатор пользователя;
    - distance — расстояние, которое пользователь проехал в текущей сессии (в метрах); 
    - duration — продолжительность сессии (в минутах) — время с того момента, как пользователь нажал кнопку «Начать поездку» до момента, как он нажал кнопку «Завершить поездку»;
    - date — дата совершения поездки.
- Подписки — `subscriptions_go.csv`:
    - subscription_type — тип подписки;
    - minute_price — стоимость одной минуты поездки по данной подписке;
    - start_ride_price — стоимость начала поездки;
    - subscription_fee	стоимость ежемесячного платежа.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__


Отличная практика - расписывать цель и основные этапы своими словами (этот навык очень поможет на фильнальном проекте).
</div>

<div class="alert alert-info">✔️ <b>Спасибо</b> буду продолжать в том же духе)

## Настройка параметров анализа 
### Импорт библиотек и настройка параметров (#settings)
<a id="settings"></a>

In [1]:
# Импортирую все необходимые библиотеки
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from matplotlib import pyplot as plt
from scipy import stats as st
from math import factorial
from scipy.stats import binom
from plotly import graph_objects as go
import plotly.express as px
from math import sqrt

import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

plt.rcParams["figure.figsize"] = (20, 5)

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Хорошо. Модули выгружены

<div class="alert alert-info">🤓

### Функции (#functions)
<a id="functions"></a>

#### Функции для предобработки данных

In [2]:
def get_count_and_share(df: pd.DataFrame, groupby: str = "city") -> pd.DataFrame:
    """
    Функция формирует и выводит сводную таблицу по одному из атрибутов (город по умолчанию),
    в которой отражает количество и долю строк каждого из этих атрибутов.
    """
    # считаю количество пользователей
    count_and_share = df.groupby(groupby).agg({groupby: "count"})

    # переименовываю столбец
    count_and_share.columns = ["count"]

    # считаю долю
    count_and_share["%_share_of_"] = round(
        (count_and_share["count"]).div(df["user_id"].count(), axis=0), 4
    )

    count_and_share = count_and_share[count_and_share["%_share_of_"] >= 0.001]

    # переименовываю столбцы финального датафрейма
    count_and_share.columns = ["count_of_" + groupby, "%_share_of_" + groupby]

    # сортирую финальный датафрейм по убыванию
    count_and_share = count_and_share.sort_values(
        by="%_share_of_" + groupby, ascending=False
    )

    count_and_share = count_and_share.style.format(
        {"%_share_of_" + groupby: "{:.2%}".format}
    ).background_gradient(cmap="Greens")
    return count_and_share

#### Функции для анализа и визуализации данных.

In [3]:
# Функция display_pivot_table формирует сводные таблицы с неограниченным количеством параметров группировки
def get_pivot_table(
    data: pd.DataFrame, base_column: str, index_name: str
) -> pd.DataFrame:
    """
    Функция формирует и выводит сводную таблицу по одному из атрибутов,
    в которой отражает сумму и долю каждого из атрибутов.
    """

    pivot_table = data.pivot_table(
        index=index_name, values=base_column, aggfunc=["count"]
    ).reset_index()
    # переименовываю столбец
    pivot_table.columns = [index_name, "count_of_users"]

    # считаю долю платящих пользователей
    pivot_table["%_share_of_" + index_name] = (
        pivot_table["count_of_users"] * 100 / pivot_table["count_of_users"].sum()
    ).round(2)

    # сортирую финальный датафрейм по убыванию
    pivot_table = pivot_table.sort_values(by="count_of_users")

    return pivot_table

In [4]:
# Функция для создания сводной таблицы с данными о поездках
def get_pivot_users_info(
    df: pd.DataFrame,
    index=["user_id", "month"],
    values=[
        "distance",
        "duration",
        "date",
        "minute_price",
        "start_ride_price",
        "subscription_fee",
        "subscription_type",
    ],
    aggfunc={
        "distance": "sum",
        "duration": "sum",
        "date": "count",
        "minute_price": "first",
        "start_ride_price": "first",
        "start_ride_price": "first",
        "subscription_fee": "first",
        "subscription_type": "first",
    },
) -> pd.DataFrame:
    pivot_table = (
        df.pivot_table(index=index, values=values, aggfunc=aggfunc)
        .reset_index()
        .rename(columns={"date": "rides_count"})
    )

    return pivot_table

In [5]:
# Функция добавляет столбец с данными об общей выручке за каждый месяц поездок пользователей
def get_month_revenue(
    df: pd.DataFrame,
    start_ride_price: str,
    subscription_fee: str,
    duration: str,
    minute_price: str,
) -> pd.DataFrame:
    """
    Функция рассчитывает выручку помесячно
    """
    start_ride_price = df["start_ride_price"] * df["rides_count"]
    subscription_fee = df["subscription_fee"]
    duration = df["duration"]
    minute_price = df["minute_price"]

    df["revenue"] = start_ride_price + subscription_fee + duration * minute_price
    return df

In [6]:
# Функция build_hist для генерации гистограмм по указанным параметрам
def build_hist(
    data: pd.Series,
    xname: str,
    title=None,
    xlabelsize=None,
    xrot=None,
    ylabelsize=None,
    yrot=None,
    ax=None,
    sharex=False,
    figsize=(20, 8),
    bins=40,
    legend=True,
):
    data.hist(figsize=figsize, bins=bins, legend=legend)
    plt.xlabel(xname)
    plt.title(title)
    plt.ticklabel_format(style="plain")
    plt.show()

## Знакомство с данными (#data)
<a id="data"></a>

In [7]:
try:
    users, rides, subscriptions = (
        pd.read_csv(
            # пользователи
            "/datasets/users_go.csv"
        ),
        pd.read_csv(
            # поездки
            "/datasets/rides_go.csv"
        ),
        pd.read_csv(
            # подписки
            "/datasets/subscriptions_go.csv"
        ),
    )
except:
    users, rides, subscriptions = (
        pd.read_csv(
            # пользователи
            "users_go.csv"
        ),
        pd.read_csv(
            # поездки
            "rides_go.csv"
        ),
        pd.read_csv(
            # подписки
            "subscriptions_go.csv"
        ),
    )
users.head()

   user_id        name  age            city subscription_type
0        1        Кира   22          Тюмень             ultra
1        2   Станислав   31            Омск             ultra
2        3     Алексей   20          Москва             ultra
3        4  Константин   26  Ростов-на-Дону             ultra
4        5       Адель   28            Омск             ultra

In [8]:
rides.head()

   user_id     distance   duration        date
0        1  4409.919140  25.599769  2021-01-01
1        1  2617.592153  15.816871  2021-01-18
2        1   754.159807   6.232113  2021-04-20
3        1  2694.783254  18.511000  2021-08-11
4        1  4028.687306  26.265803  2021-08-28

In [9]:
subscriptions.head()

  subscription_type  minute_price  start_ride_price  subscription_fee
0              free             8                50                 0
1             ultra             6                 0               199

Предпросмотр данных показывает, что датасет о поездках `rides` детализирует информацию о пользователях датасета `users` и может быть связан по индексу — айди пользователя `user_id`.  
Датасет `subscriptions` о подписках содержит данные о стоимости и тарифах, на её основании может быть рассчитана стоимость каждой из поездок датасета `rides` и общей суммы затрат каждого из пользователей датасета `users` по индексу — тип подписки `subscription_type`.  

Приступаю к предобработке данных.

<div class="alert alert-block alert-success">✔️
    
__Комментарий от ревьюера №1__
    
Отлично! Первый взгляд на данные есть

<div class="alert alert-info">👩🏻‍🎓 Спасибо

## Предобработка данных (#data_preprocessing)
<a id="data"></a>

In [10]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1565 entries, 0 to 1564
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1565 non-null   int64
 1   name               1565 non-null   object
 2   age                1565 non-null   int64
 3   city               1565 non-null   object
 4   subscription_type  1565 non-null   object
dtypes: int64(2), object(3)
memory usage: 61.3+ KB

In [11]:
# Проверяю распределение пользователей по городам и проверяю столбец на наличие опечаток и ошибок
# с помощью функции 'get_count_and_share()'
get_count_and_share(users, "city")

При просмотре городов пользователей не обнаружено скрытых дубликатов и ошибок.

In [12]:
# Проверяю распределение пользователей по возрасту с помощью функции 'get_count_and_share()'
get_count_and_share(users, "age")

Ошибочных данных в столбце `age` не обнаружено.

In [13]:
# Проверяю распределение пользователей по типам подписки и проверяю на наличие опечаток и ошибок с помощью функции 'get_count_and_share()'
get_count_and_share(users, "subscription_type")

Дубликатов, пропусков и ошибок в столбце `subscription_type` не обнаружено.

In [14]:
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18068 entries, 0 to 18067
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   18068 non-null  int64
 1   distance  18068 non-null  float64
 2   duration  18068 non-null  float64
 3   date      18068 non-null  object
dtypes: float64(2), int64(1), object(1)
memory usage: 564.8+ KB

In [15]:
# преобразование данных о дате
rides["date"] = pd.to_datetime(rides["date"])

In [16]:
# добавляю столбец с месяцем поездки на основании данных столбца `date`
rides["month"] = rides["date"].values.astype("datetime64[M]")
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18068 entries, 0 to 18067
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   18068 non-null  int64
 1   distance  18068 non-null  float64
 2   duration  18068 non-null  float64
 3   date      18068 non-null  datetime64[ns]
 4   month     18068 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1)
memory usage: 705.9 KB

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__

Хорошо бы проверить за какой период у нас данные. Проверить столбец длительности на предмет наличия аномалий. Например, если у нас разные года то январь 2021 и январь 2022 будут под одной цифрой (1). 
</div>

<div class="alert alert-info">✔️ <b>Спасибо 🤝</b> 

вывела ниже все месяцы методом value_counts() </div>

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №2__

Учтено

In [17]:
rides["month"].value_counts()

2021-01-01    1585
2021-05-01    1560
2021-06-01    1553
2021-03-01    1544
2021-07-01    1529
2021-12-01    1527
2021-08-01    1518
2021-09-01    1517
2021-04-01    1506
2021-10-01    1475
2021-11-01    1418
2021-02-01    1336
Name: month, dtype: int64

In [18]:
rides["distance"].value_counts()

741.545359     1
4158.226381    1
3672.118870    1
4533.004089    1
2437.274120    1
              ..
2949.530545    1
3289.893471    1
3047.554085    1
2931.718067    1
4031.935032    1
Name: distance, Length: 18068, dtype: int64

In [19]:
rides["duration"].value_counts()

0.500000     95
22.184080     1
25.866000     1
22.837062     1
19.173800     1
             ..
18.843765     1
17.644888     1
22.477965     1
19.745218     1
16.537044     1
Name: duration, Length: 17974, dtype: int64

In [20]:
rides["date"].value_counts()

2021-12-22    72
2021-01-12    70
2021-12-27    69
2021-08-20    67
2021-06-09    67
              ..
2021-11-07    35
2021-07-30    35
2021-12-15    34
2021-02-02    34
2021-07-03    31
Name: date, Length: 364, dtype: int64

In [21]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_type  2 non-null      object
 1   minute_price       2 non-null      int64
 2   start_ride_price   2 non-null      int64
 3   subscription_fee   2 non-null      int64
dtypes: int64(3), object(1)
memory usage: 192.0+ bytes

In [22]:
users.duplicated().value_counts()

False    1534
True       31
dtype: int64

In [23]:
rides.duplicated().value_counts()

False    18068
dtype: int64

In [24]:
subscriptions.duplicated().value_counts()

False    2
dtype: int64

In [25]:
users = users.drop_duplicates()
users.duplicated().value_counts()

False    1534
dtype: int64

В таблице `users` обнаружена 31 строка-дубликат. Удалила их из датафрейма.  
В других датасетах дубликатов не обнаружено. Проверяю датасеты на наличие пропусков.

In [26]:
# считаю долю пропусков в каждом из столбцов датафрейма 'users'
users.isna().mean()

user_id              0.0
name                 0.0
age                  0.0
city                 0.0
subscription_type    0.0
dtype: float64

In [27]:
# считаю долю пропусков в каждом из столбцов датафрейма 'rides'
rides.isna().mean()

user_id     0.0
distance    0.0
duration    0.0
date        0.0
month       0.0
dtype: float64

In [28]:
# считаю долю пропусков в каждом из столбцов датафрейма 'subscriptions'
subscriptions.isna().mean()

subscription_type    0.0
minute_price         0.0
start_ride_price     0.0
subscription_fee     0.0
dtype: float64

Пропуски в датасетах не обнаружены.

**Первичное знакомство с датасетами позволило найти и удалить дубликаты, оценить распределение пользователей по городам и типам подписки, проверить данные на пропуски и преобразовать тип данных столбца с датой.**  

**Теперь можно исследовать данные подробнее.**

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Проверка на дубликаты - основа предобработки данных

## Исследовательский анализ данных (#research_analysis)
<a id="data"></a>

In [29]:
# Распределение пользователей по городам
users_pivot_city = get_pivot_table(users, "user_id", "city")

fig = px.pie(users_pivot_city, names="city", values="%_share_of_city")
fig.update_layout(
    legend_orientation="h",
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по городам",
    xaxis_title="Количество пользователей",
    yaxis_title="Названия городов",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__

Если категорий больше 3-4, корректнее использовать столбчатую диаграмму

<div class="alert alert-info">✔️ <b>Ок, спасибо</b> 

Я сначала её и использовала, но потом подумала, что круговая нагляднее демонстрирует небольшую разницу долей пользователей по городам.  Ниже добавила bar с городами. </div>

In [30]:
fig = px.bar(users_pivot_city, x="count_of_users", y="city", text="%_share_of_city")
fig.update_layout(
    legend_orientation="h",
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по городам",
    xaxis_title="Количество пользователей",
    yaxis_title="Названия городов",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №2__

Отличный и наглядный график 👍
    
Здорово, когда он подписан. Так быстрее понять о чем идёт речь на нём.
    
</div>

География пользователей датасета распределена между 8 городами с незначительным разницей в долях.  
При этом самая маленькая доля пользователей в Москве `(10,95%)`, городом-лидером по количеству пользователей стал Пятигорск `(14,28%)`.

In [31]:
# Распределение пользователей по способу использования приложения
users_pivot_subscription_type = get_pivot_table(users, "user_id", "subscription_type")

fig = px.pie(
    users_pivot_subscription_type,
    names="subscription_type",
    values="%_share_of_subscription_type",
    #     x="count_of_users",
    #     y="subscription_type",
    #     text="%_share_of_subscription_type",
)
fig.update_layout(
    legend_orientation="h",
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по типу подписки",
    xaxis_title="Количество пользователей",
    yaxis_title="Тип подписки",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()

Большая часть пользователей `(54,06%)` использует приложение без подписки.  
Их доля на `8,12%` больше количества платящих.  
В дальнейшем проанализирую особенности каждой из групп пользователей.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Пользователей с подпиской немного меньше, тем не менее у компании-прокатчика есть неплохая база постоянных клиентов.

In [32]:
# Распределение пользователей по возрасту
users_pivot_age = get_pivot_table(users, "user_id", "age")

fig = px.bar(
    users_pivot_age,
    x="age",
    y="count_of_users",
    text="%_share_of_age",
)
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по возрасту",
    xaxis_title="Возраст пользователей",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()

Основные возрастные группы пользователей (с долей более 5%) — 21-28 лет суммарно составляют  `(63,88%)`.  
Доли пользователей каждой из других возрастных групп менее `5%`, а доли пользователей в возрасте младше 16 лет и старше 34 лет менее `1%`.   
В дальнейшем необходимо сопоставить данные о долях платящих пользователей с разбивкой по возрасту.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Основная часть пользователей возрастом от 22 до 28 лет. Все что меньше 15 лет и больше 40 можно считать редкими значениями.

In [33]:
# Распределение пользователей по расстоянию, преодолённому за одну поездку
rides_pivot_distance = get_pivot_table(rides, "user_id", "distance")

fig = px.histogram(rides_pivot_distance, x="distance", y="count_of_users")
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по расстоянию поездок",
    xaxis_title="Расстояние поездок, м",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()
rides_pivot_distance["distance"].describe()

count    18068.000000
mean      3070.659976
std       1116.831209
min          0.855683
25%       2543.226360
50%       3133.609994
75%       3776.222735
max       7211.007745
Name: distance, dtype: float64

Дистанция поездок основной доли пользователей в пределах 2450 - 3750 метров.  
Медианное расстояние поездки 3 133,61 метра при максимальном 7 211 метра, минимальном — 0,86 метра и среднем — 1 116,83 метра.  

Большой разрыв между медианным и средним значением говорит о наличии вбросов. На графике некоторая часть пользователей использует самокаты для коротких поездок – до 1500 метров.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Основная часть поездок занимает от 2500 до 3800 метров. Медиана 3133 метра. Поездки на расстояние более 5 км редки. Однако на гистограмме видно, что некоторая часть пользователей использует самокаты для коротких поездок - до 1500 м.

In [34]:
# Распределение пользователей по продолжительности сессии, преодолённому за одну поездку
rides_pivot_duration = get_pivot_table(rides, "user_id", "duration")

fig = px.histogram(rides_pivot_duration, x="duration", y="count_of_users")
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение пользователей по продолжительности сессии",
    xaxis_title="Продолжительность сессии, минут",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
fig.show()
rides_pivot_duration["duration"].describe()

count    17974.000000
mean        17.895513
std          5.976666
min          0.500000
25%         13.669653
50%         17.713710
75%         21.746921
max         40.823963
Name: duration, dtype: float64

Из графика отмечаю выброс по продолжительности сессии до 1 минуты и сверх 35 минут. Медианное значение продолжительности сессии — 17,71 минуты при среднем 5,98 минут.  
Максимальное значение 40,82 минут, минимальное — 0,5 минут.  
Такой разброс свидетельствует о наличии выбросов в данных. В дальнейшем следует разделить данные о продолжительности сессии по типам подписки.

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__

Хорошо бы графики подкрепить боксплотом

<div class="alert alert-block alert-info"> 🤔 Да, я тоже думала об этом, но данные несопоставимы на этом этапе, мне кажется.  
  
🤓Только если отдельный датафрейм создать и сравнивать между собой duration, distance и прочие 🤷🏻‍♀️  
Или я чего-то не понимаю🤔

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №2__

Не совсем. Посмотреть распределение каждого признака(столбца) с помощью диаграммы размаха
    
    plt.boxplot(df[])

## Объединение данных (#data_merging)
<a id="data"></a>

Для подробного анализа влияния наличия / отсутствия подписки на частоту и интенсивность использования приложения объединяю данные о поздках в один датафрейм и проанализирую данные о продолжительности использования приложения и расстоянию поездок для каждой из групп пользователей.

In [35]:
# объединяю данные о пользователях и поездках
user_rides = users.merge(rides, on="user_id", how="left")

# Вывожу случйные 5 строк объединённого датафрейма


user_rides.sample(5)

,user_id,name,age,city,subscription_type,distance,duration,date,month
9633,932,Антон,25,Сочи,free,4398.804198,21.996739,2021-10-26,2021-10-01
15629,1364,Ян,31,Тюмень,free,4375.042408,0.500000,2021-10-23,2021-10-01
4004,432,Мадина,21,Омск,ultra,2766.114962,14.064460,2021-01-14,2021-01-01
9118,895,Мирон,25,Сочи,free,2449.530184,16.067993,2021-06-28,2021-06-01
13627,1219,Ксения,25,Пятигорск,free,834.474060,12.854387,2021-04-12,2021-04-01

In [36]:
# вывожу информацию о полученном датафрейме
user_rides.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18068 entries, 0 to 18067
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            18068 non-null  int64
 1   name               18068 non-null  object
 2   age                18068 non-null  int64
 3   city               18068 non-null  object
 4   subscription_type  18068 non-null  object
 5   distance           18068 non-null  float64
 6   duration           18068 non-null  float64
 7   date               18068 non-null  datetime64[ns]
 8   month              18068 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(3)
memory usage: 1.4+ MB

In [37]:
# объединяю данные о поездках и тарифах на них
users_info = user_rides.merge(subscriptions, on="subscription_type", how="left")
# Вывожу случйные 5 строк объединённого датафрейма


users_info.sample(5)

,user_id,name,age,city,subscription_type,distance,duration,date,month,minute_price,start_ride_price,subscription_fee
14339,1268,Юлия,26,Краснодар,free,4158.417101,12.396043,2021-05-18,2021-05-01,8,50,0
2317,247,Арина,22,Ростов-на-Дону,ultra,2701.053173,16.588386,2021-03-04,2021-03-01,6,0,199
9519,924,Мария,23,Пятигорск,free,2714.588628,17.616390,2021-02-27,2021-02-01,8,50,0
14629,1288,Матвей,33,Ростов-на-Дону,free,3978.657563,22.564182,2021-12-24,2021-12-01,8,50,0
8077,816,Максим,28,Сочи,free,654.609974,10.454787,2021-09-16,2021-09-01,8,50,0

In [38]:
# вывожу информацию о полученном датафрейме
users_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18068 entries, 0 to 18067
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            18068 non-null  int64
 1   name               18068 non-null  object
 2   age                18068 non-null  int64
 3   city               18068 non-null  object
 4   subscription_type  18068 non-null  object
 5   distance           18068 non-null  float64
 6   duration           18068 non-null  float64
 7   date               18068 non-null  datetime64[ns]
 8   month              18068 non-null  datetime64[ns]
 9   minute_price       18068 non-null  int64
 10  start_ride_price   18068 non-null  int64
 11  subscription_fee   18068 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(3)
memory usage: 1.8+ MB

После объединения данных таблиц с информацией о пользователях, их поездках и тарифах поездок вывожу информацию о полученном датафрейме для проверки отсутствия потерь данных — в итоговом датафрейме 18 068 строк, как и в одном из первичных датафреймов — `rides` с информацией о поездках. Это подтверждает отсутствие потерь в данных.  

В далнейшем создаю два новых датафрейма с полной информацией о пользователях и их поездках для групппы с подпиской и без.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Отлично. Проверка размерности датасетов проведена

In [39]:
# выделяю данные о поездках пользователей с подпиской
users_subscribes = users_info[users_info["subscription_type"] == "ultra"]
# Вывожу первые 5 строк объединённого датафрейма


users_subscribes.head()

,user_id,name,age,city,subscription_type,distance,duration,date,month,minute_price,start_ride_price,subscription_fee
0,1,Кира,22,Тюмень,ultra,4409.919140,25.599769,2021-01-01,2021-01-01,6,0,199
1,1,Кира,22,Тюмень,ultra,2617.592153,15.816871,2021-01-18,2021-01-01,6,0,199
2,1,Кира,22,Тюмень,ultra,754.159807,6.232113,2021-04-20,2021-04-01,6,0,199
3,1,Кира,22,Тюмень,ultra,2694.783254,18.511000,2021-08-11,2021-08-01,6,0,199
4,1,Кира,22,Тюмень,ultra,4028.687306,26.265803,2021-08-28,2021-08-01,6,0,199

In [40]:
# вывожу информацию о полученном датафрейме
users_subscribes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6500 entries, 0 to 6499
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            6500 non-null   int64
 1   name               6500 non-null   object
 2   age                6500 non-null   int64
 3   city               6500 non-null   object
 4   subscription_type  6500 non-null   object
 5   distance           6500 non-null   float64
 6   duration           6500 non-null   float64
 7   date               6500 non-null   datetime64[ns]
 8   month              6500 non-null   datetime64[ns]
 9   minute_price       6500 non-null   int64
 10  start_ride_price   6500 non-null   int64
 11  subscription_fee   6500 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(3)
memory usage: 660.2+ KB

In [41]:
# выделяю данные о поездках пользователей без подписки
users_unsubscribes = users_info[users_info["subscription_type"] == "free"]
# Вывожу первые 5 строк объединённого датафрейма
users_unsubscribes.head()

,user_id,name,age,city,subscription_type,distance,duration,date,month,minute_price,start_ride_price,subscription_fee
6500,700,Айдар,22,Омск,free,2515.690719,14.944286,2021-01-02,2021-01-01,8,50,0
6501,700,Айдар,22,Омск,free,846.932642,16.234663,2021-02-01,2021-02-01,8,50,0
6502,700,Айдар,22,Омск,free,4004.434142,20.016628,2021-02-04,2021-02-01,8,50,0
6503,700,Айдар,22,Омск,free,1205.911290,9.782872,2021-02-10,2021-02-01,8,50,0
6504,700,Айдар,22,Омск,free,3047.379435,17.427673,2021-02-14,2021-02-01,8,50,0

In [42]:
# Распределение по расстоянию поездок пользователей с подпиской
rides_users_subscribes_pivot_distance = get_pivot_table(
    users_subscribes, "user_id", "distance"
)

fig = px.histogram(
    rides_users_subscribes_pivot_distance, x="distance", y="count_of_users"
)
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение по расстоянию поездок пользователей с подпиской",
    xaxis_title="Расстояние поездок, м",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
# визуализирую данные о расстоянии поездок пользователей с подпиской
fig.show()
# Вывожу таблицу нюансов распределения расстоянии поездок пользователей с подпиской методом describe()
rides_users_subscribes_pivot_distance["distance"].describe()

count    6500.000000
mean     3115.445388
std       836.895330
min       244.210438
25%      2785.444017
50%      3148.637229
75%      3560.574425
max      5699.769662
Name: distance, dtype: float64

Среднее расстояние поездки пользователей с подпиской 836,895 метра при медиане – 3 148,637 метра, минимальном значении — 244,21 метра и максимальном — 5699,77 метра. График и большой разброс в нижнюю границу указывают на наличие вбросов — поездок на короткие расстояния.

In [43]:
# Распределение по расстоянию поездок пользователей без подписки
rides_users_unsubscribes_pivot_distance = get_pivot_table(
    users_unsubscribes, "user_id", "distance"
)

fig = px.histogram(
    rides_users_unsubscribes_pivot_distance, x="distance", y="count_of_users"
)
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение по расстоянию поездок пользователей без подписки",
    xaxis_title="Расстояние поездок, м",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
# визуализирую данные о расстоянии поездок пользователей без подписки
fig.show()
# Вывожу таблицу нюансов распределения расстоянии поездок пользователей без подписки методом describe()
rides_users_unsubscribes_pivot_distance["distance"].describe()

count    11568.000000
mean      3045.495282
std       1246.173806
min          0.855683
25%       2366.562689
50%       3114.648465
75%       3905.697894
max       7211.007745
Name: distance, dtype: float64

Среднее расстояние поездки пользователей с подпиской 1 246,17 метра при медиане – 3 114,648 метра, минимальном значении — 0,855 метра и максимальном — 7 211 метра. График и большой разброс в нижнюю границу указывают на наличие вбросов — поездок на короткие расстояния.  

Однако, разброс среднего и медианного значений расстояния пользователей с подпиской гораздо меньше. В дальнейшем следует оценить выручку каждой из групп.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

У пользователей без подписки значительно больше коротких поездок - до 1 км и в целом максимальная дальность поездки выше, чем у платных пользователей.

In [44]:
# Распределение по продолжительности сессии пользователей с подпиской
rides_users_subscribes_pivot_duration = get_pivot_table(
    users_subscribes, "user_id", "duration"
)

fig = px.histogram(
    rides_users_subscribes_pivot_duration, x="duration", y="count_of_users"
)
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение по продолжительности сессии пользователей с подпиской",
    xaxis_title="Продолжительность сессии, минут",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
# визуализирую данные о продолжительности использования приложения пользователей с подпиской
fig.show()
# Вывожу таблицу нюансов распределения продолжительности сессии пользователей с подпиской методом describe()
rides_users_subscribes_pivot_duration["duration"].describe()

count    6500.000000
mean       18.541985
std         5.572048
min         3.760353
25%        14.524654
50%        18.178153
75%        21.884129
max        40.823963
Name: duration, dtype: float64

Общее количество поездок пользователей с подпиской составило 6500.  
Средняя продолжительность использования приложения пользователями с подпиской 5,57 минут при медиане – 18,18 минут, минимальном значении — 3,76 минут и максимальном — 40,82 минут.  
Продолжительность сессии пользователей с подпиской распределена нормальным образом, что наглядно отражено на графике.

In [45]:
# Распределение по продолжительности сессии пользователей без подписки
rides_users_unsubscribes_pivot_duration = get_pivot_table(
    users_unsubscribes, "user_id", "duration"
)

fig = px.histogram(
    rides_users_unsubscribes_pivot_duration, x="duration", y="count_of_users"
)
fig.update_layout(
    legend=dict(x=0.5, xanchor="center"),
    title="Распределение по продолжительности сессии пользователей без подписки",
    xaxis_title="Продолжительность сессии, минут",
    yaxis_title="Количество пользователей",
    margin=dict(l=0, r=0, t=30, b=0),
)
# визуализирую данные о продолжительности использования приложения пользователей без подписки
fig.show()
# Вывожу таблицу нюансов распределения продолжительности сессии пользователей без подписки методом describe()
rides_users_unsubscribes_pivot_duration["duration"].describe()

count    11474.000000
mean        17.529287
std          6.164391
min          0.500000
25%         13.084922
50%         17.383480
75%         21.637816
max         34.948498
Name: duration, dtype: float64

Количество поездок пользователей без подписки почти в два раза больше количества поездок подписчиков приложения.  
Средняя продолжительность использования приложения пользователями без подписки 6,16 минут при медиане – 17,38 минут, минимальном значении — 0,5 минут и максимальном — 34,95 минут.  
График демонстрирует большое количество вбросов с продолжительностью сессии менее 1 минуты.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

В целом картина такая же - распределение внутри категорий имеют одинаковый профиль (и одинаковый с профилем распределения до разбивки на категории - строили на ранних этапах), но в каждом из диапазонов бесплатных пользователей чуть больше, но их, как мы помним, и в целом больше.

Краевые значения (минимум и максимум) у бесплатных пользователей смещены влево относительно платных подписчиков - стоимость минуты все-таки больше, значит часть пользователей торопится завершить поездки за меньший срок. Но при этом визуально среднее значение не сильно смещено

## Подсчёт выручки (#revenue_calculation)
<a id="data"></a>

Для подсчёта суммированных данных каждого из пользователей создаю агрегированный датафрейм с суммарным расстоянием, количеством поездок и суммарному времени каждого из пользователей за каждый месяц использования приложения на основании датафрейма `users_info`.

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__
    
Нет проверки на пропуски в сводной таблице перед расчетом выручки

<div class="alert alert-block alert-info"> 🤔 Я же использую проверенный на предыдущем этапе датафрейм. 
   
🤓Выведу ещё раз ниже с комментом

In [46]:
# Для расчёта выручки использую данные датафрейма полученного при объединении
# Ещё раз выведу информацию о датафрейме для проверки полноты
users_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18068 entries, 0 to 18067
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            18068 non-null  int64
 1   name               18068 non-null  object
 2   age                18068 non-null  int64
 3   city               18068 non-null  object
 4   subscription_type  18068 non-null  object
 5   distance           18068 non-null  float64
 6   duration           18068 non-null  float64
 7   date               18068 non-null  datetime64[ns]
 8   month              18068 non-null  datetime64[ns]
 9   minute_price       18068 non-null  int64
 10  start_ride_price   18068 non-null  int64
 11  subscription_fee   18068 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(3)
memory usage: 1.8+ MB

In [47]:
# округляю данные о продолжительности поездок до минут методом ceil
users_info["duration"] = np.ceil(users_info["duration"])

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Отлично, что используешь именно np.ceil(). Грамотный шаг

<div class="alert alert-block alert-info"> Спасибо🤓

In [48]:
# строю сводную таблицу с данными о поездках за каждый месяц каждого из пользователей
rides_df = get_pivot_users_info(users_info)

In [49]:
# Добавляю в сводную таблицу столбец с выручкой с помщью функции
get_month_revenue(
    rides_df, "start_ride_price", "subscription_fee", "duration", "minute_price"
)

,user_id,month,rides_count,distance,duration,minute_price,start_ride_price,subscription_fee,subscription_type,revenue
0,1,2021-01-01,2,7027.511294,42.0,6,0,199,ultra,451.0
1,1,2021-04-01,1,754.159807,7.0,6,0,199,ultra,241.0
2,1,2021-08-01,2,6723.470560,46.0,6,0,199,ultra,475.0
3,1,2021-10-01,2,5809.911100,32.0,6,0,199,ultra,391.0
4,1,2021-11-01,3,7003.499363,56.0,6,0,199,ultra,535.0
...,...,...,...,...,...,...,...,...,...,...
11326,1534,2021-06-01,2,3409.468534,26.0,8,50,0,free,308.0
11327,1534,2021-08-01,2,7622.453034,48.0,8,50,0,free,484.0
11328,1534,2021-09-01,1,4928.173852,23.0,8,50,0,free,234.0
11329,1534,2021-11-01,4,13350.015305,78.0,8,50,0,free,824.0
11330,1534,2021-12-01,1,2371.711192,16.0,8,50,0,free,178.0

**Итоговая таблица содержит информацию о пользователях, количестве поездок за указанный месяц, расстоянии, времени использования приложения, ценах, тарифе и общей сумме выручки за месяц.**   
**На основании этих данных можно проводить проверку гипотез для каждой из категорий.**

<div class="alert alert-block alert-danger">✍
    

__Комментарий от ревьюера №1__

    
Некорректный расчёт пользователей без подписки. Например для 11329 строки. Не учитываешь старт за каждую поездку

<div class="alert alert-info">🔥 <b>Спасибо, точно!</b> 

Исправила формулу в функции, теперь всё верно 🤓  </div>

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №2__

Корректная реализация. Молодец)

## Проверка гипотез (#hypothesis_testing)
<a id="data"></a>

Продакт-менеджеры сервиса хотят увеличить количество пользователей с подпиской. Для этого они будут проводить различные акции, но сначала нужно выяснить несколько важных моментов.  

Первая гипотеза, котрую необходимо проверить — пользователи с подпиской тратят больше времени на поездки и могут быть «выгоднее» для компании. Для её проверки исследую данные о продолжительности каждой сессии — отдельно для подписчиков и тех, у кого нет подписки.  

Для проверки гипотезы сравню среднюю продолжительность использования приложения для пользователей с подпиской и без неё.  
H0: средняя продолжительность использования приложения не увеличивается при покупке подписки.  
H1: средняя продолжительность использования приложения увеличивается при покупке подписки.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Верная интерпретация нулевой и альтернативной гипотез
</div>

In [50]:
print(
    f' Средняя продолжительность использования приложения пользователей с подпиской: {np.mean(users_subscribes["duration"])}'
)
print(
    f' Средняя продолжительность использования приложения пользователей без подписки: {np.mean(users_unsubscribes["duration"])}'
)

# уровень статистической значимости
alpha = 0.05

results = st.ttest_ind(
    users_subscribes["duration"], users_unsubscribes["duration"], alternative="greater"
)
# выведем полученное p-value
print("p-значение:", results.pvalue)

 Средняя продолжительность использования приложения пользователей с подпиской: 18.54198516280583
 Средняя продолжительность использования приложения пользователей без подписки: 17.39090929866399
p-значение: 1.2804098316645618e-34

**Среднее значение — на 1,15 минут (18,54 - 17,39) или на 6,2%.**  
**При статистической значимости 5% такое изменение действительно существенно, а значит нулевая гипотеза отвергается.**  

Вторая гипотеза, котрую необходимо проверить — среднее расстояние, которое проезжают пользователи с подпиской за одну поездку, не превышает 3130 метров.  

Для проверки гипотезы необходимо сравнить среднее расстояние пользователей с подпиской с предположенным в нулевой гипотезе числом (t-тест).  
H0: среднее расстояние, которое проезжают пользователи с подпиской за одну поездку превышает 3130 метров.  
H1: среднее расстояние, которое проезжают пользователи не больше 3130 метров.

In [51]:
print(
    f'Среднее расстояние, которое проезжают пользователи с подпиской за одну поездку: {np.mean(users_subscribes["distance"])}'
)

screens = users_subscribes["distance"]

prev_screens_value = 3130

alpha = 0.05  # уровень статистической значимости

results = st.ttest_1samp(screens, prev_screens_value, alternative="greater")

print("p-значение:", results.pvalue)

if results.pvalue > alpha:
    print("Отвергаем нулевую гипотезу")
else:
    print("Не отвергаем нулевую гипотезу")
results

Среднее расстояние, которое проезжают пользователи с подпиской за одну поездку: 3115.4453880370247
p-значение: 0.9195368847849785
Отвергаем нулевую гипотезу

Ttest_1sampResult(statistic=-1.402123166869486, pvalue=0.9195368847849785)

<div class="alert alert-block alert-warning">📝
    

__Комментарий от ревьюера №1__

Смотри, поскольку оптимальное расстояние по износу составляет 3130 м, значит большее расстояние приводит к повышенному износу самоката. Следовательно имеет смысл проверить одностороннюю гипотезу, что расстояние, которое проезжают пользователи с подпиской не превышает оптимального расстояния в 3130 м.

То есть в статистическом тесте стоит поставить параметр alternative = 'greater' и изменить Н1 на знак `больше`

<div class="alert alert-block alert-info"> 🤔  
Перечитала ещё раз теорию, видимо, не ложится пока этот метод. Пройду курс Карпова, может уляжется 🤪 Пока исправила по рекомендациям, посмотри, пожалуйста, ещё раз

**Среднее расстояние — 3115.4453880370247, что меньше предполагаемого среднего на 14,55 м или на 0,4%**  

Третья гипотеза, котрую необходимо проверить — помесячная выручка от пользователей с подпиской по месяцам выше, чем выручка от пользователей без подписки.  

Для проверки гипотезы необходимо сравнить две независимые выборки о выручке пользователей с подпиской и без.  
H0: Средняя помесячная выручка от группы пользователей с подпиской равна средней выручке пользователей без подписки.  
H1: Средняя помесячная выручка от группы пользователей с подпиской выше, чем выручка от пользователей без подписки.

In [52]:
# получаем датафреймы с выручкой  пользователей с подпиской и без
rides_subscibes = rides_df[rides_df["subscription_type"] == "ultra"]
rides_unsubscibes = rides_df[rides_df["subscription_type"] == "free"]

# вывожу средние помесячные выручки для каждой из групп пользователей
print(rides_subscibes["revenue"].mean())
print(rides_unsubscibes["revenue"].mean())

alpha = 0.05  # уровень статистической значимости
# если p-value окажется меньше него, отвергнем гипотезу

results = st.ttest_ind(
    rides_subscibes["revenue"], rides_unsubscibes["revenue"], alternative="greater"
)

print("p-значение:", results.pvalue)

if results.pvalue < alpha:
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

362.7921906022502
328.6413651073845
p-значение: 1.8850394384715216e-31
Отвергаем нулевую гипотезу

<div class="alert alert-block alert-info"> Исправила комментарии после пересчёта выручки:   

Средняя помесячная выручка пользователей с подпиской — 362,79 руб.   
Средняя помесячная выручка пользователей без подписки — 328,64 руб.  
Разница составляет 34,15 руб (9,41% от средней выручки первой группы)</div>   

**Отвергаю нулевую гипотезу о равенстве средней помесячной выручки для каждой из групп пользователей. Есть основания говорить, что пользователи с подпиской тратят в сервисе больше денег.**  

Последняя гипотеза, которую можно было бы проверить — снижение количества обращений пользователей в техподдержку из-за обновлений серверов.  
Для этого следовало бы проверять гипотезу о равенстве среднего значения генеральной совокупности до и после изменения.  
Аргументы: наборы данных — парные выборки до и после обновления серверов.  
Для проверки следовало бы воспользоваться методом `scipy.stats.ttest_rel()` с аргументом `alternative = 'greater'`.

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №1__

Для решения потребуется тест на равенство средних для зависимых выборок, до и после изменений.>

## Распределения (#distributions)
<a id="data"></a>

<div class="alert alert-block alert-info"> Вывод: в процессе анализа были проверены 3 гипотезы.  
  
— о продолжительности сессии пользователей с подпиской и без;  
— об оптимальном расстоянии одной поездки в 3130 метров;  
— о размере помесячной выручки пользователей с подпиской.  

В процессе проверки:   
- была отвергнута гипотеза о том, что продолжительность сессии при покупке подписки не меняется;
- была отвергнута гипотеза о том, что среднее расстояние, которое проезжают пользователи с подпиской за одну поездку превышает 3130 метров;
- была отвергнута гипотеза о том, что средняя помесячная выручка от пользователей с подпиской равна средней выручке пользователей без подписки.  

Результаты проверки гипотез свидетельствуют о том, что пользователи с подпиской могу быть выгодны для компании, а значит следует разрабатывать маркетинговые мероприятия для увеличения количества подписчиков.

<div class="alert alert-block alert-danger">✍
    

__Комментарий от ревьюера №1__

Итоговый вывод завершает твое исследование. А его нету...В идеале добавить рекомендации бизнесу
</div>

<div class="alert alert-block alert-success">✔️
    

__Комментарий от ревьюера №2__

Cогласен с рекомендацией

<div class="alert alert-block alert-warning">📝
Комментарий от ревьюера №1 </b> 



У тебя получилась очень сильная и хорошая работа. Здорово, что расчеты ты сопровождаешь иллюстрациями, а так же не забываешь про комментарии, твой проект интересно проверять. 

---

Нужно поправить:

1) Подсчёт выручки

2) Финальный вывод

3) Подправить выводы, после изменений

----


Если у тебя будут какие-то вопросы по моим комментариям - обязательно пиши! Буду ждать работу на повторное ревью :)</div>

<div style="border:solid blue 3px; padding: 20px">
<div class="alert alert-block alert-success">✔️
    

__Коментарий от ревьюера №2__


В остальном всё чудно😊. Твой проект так и просится на github =)   
    
Поздравляю с успешным завершением проекта 😊👍
И желаю успехов в новых работах 😊
    
---
    
От себя хочу порекомендовать тебе отличный метариал по статистике. 
    
* Курс "Вероятность и статистика" | Глеб Михайлов (free): https://www.youtube.com/playlist?list=PLQJ7ptkRY-xbHLLI66KdscKp_FJt0FsIi
    
* Методы обнаружения выбросов: https://youtu.be/TOK7Kq7x0yc
    

</div>